export {
  B2bApprovalRulesPage,
  B2bBuyersPage,
  B2bCatalogPage,
  B2bCatalogVisibilityPage,
  B2bCompaniesPage,
  B2bIntegrationsPage,
  B2bInsightsPage,
  B2bInventoryPage,
  B2bOrdersPage,
  B2bPaymentsPage,
  B2bPricingPage,
  B2bProductMatchesPage,
  B2bQuotesPage,
  B2bShoppingListsPage,
  B2bWorkspacePage,
} from './components/B2bWorkspacePage';
